services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./workspace:/opt/spark/workspace
      - ./shared:/opt/spark/shared
    networks:
      - my_network

  spark-worker:
    image: bitnami/spark:latest
    depends_on:
      - spark-master
    deploy:
      replicas: 2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./workspace:/opt/spark/workspace
      - ./shared:/opt/spark/shared
    networks:
      - my_network

  vscode:
    build: ./vscode
    container_name: vscode
    restart: always
    ports:
      - "9000:9000" # Code-Server (VS Code in browser)
      - "9001:9001" # Jupyter Notebook
    volumes:
      - ./shared:/home/coder/workspace/shared
      - ./workspace:/home/coder/workspace
    environment:
      - PASSWORD=@mensenvau!12345 # password
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - my_network

networks:
  my_network: # Umumiy tarmoq
    driver: bridge
